# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMUqdBGqXLDdb9IEEdMeiXCmogXbAxXd
"""

import streamlit as st

st.set_page_config(page_title="AI Vision App", layout="centered")
st.title("👁️‍🗨️ Real-Time AI Vision App")

st.markdown("""
Welcome to the **Real-Time AI Vision App** powered by **MediaPipe** and **Streamlit**.
- Navigate using the sidebar.
- Enjoy real-time detection through your webcam!
""")