# -*- coding: utf-8 -*-
"""1_RealTime_Face_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMUqdBGqXLDdb9IEEdMeiXCmogXbAxXd
"""

import streamlit as st
import cv2
import mediapipe as mp

st.title("😀 Real-Time Face Detection")

mp_face = mp.solutions.face_detection
mp_drawing = mp.solutions.drawing_utils

face_detection = mp_face.FaceDetection(model_selection=0, min_detection_confidence=0.5)

cap = cv2.VideoCapture(0)
frame = st.empty()

while True:
    ret, img = cap.read()
    if not ret:
        st.warning("Webcam not accessible.")
        break

    img = cv2.flip(img, 1)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = face_detection.process(img_rgb)

    if results.detections:
        for detection in results.detections:
            mp_drawing.draw_detection(img, detection)

    frame.image(img, channels="BGR")

cap.release()