# -*- coding: utf-8 -*-
"""2_RealTime_Object_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMUqdBGqXLDdb9IEEdMeiXCmogXbAxXd
"""

import streamlit as st
import cv2
import mediapipe as mp

st.title("📦 Real-Time 3D Object Detection (Cup)")

mp_objectron = mp.solutions.objectron
mp_drawing = mp.solutions.drawing_utils

objectron = mp_objectron.Objectron(
    static_image_mode=False,
    max_num_objects=5,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.7,
    model_name='Cup'
)

cap = cv2.VideoCapture(0)
frame = st.empty()

while True:
    ret, img = cap.read()
    if not ret:
        st.warning("Webcam not accessible.")
        break

    img = cv2.flip(img, 1)
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = objectron.process(img_rgb)
    img = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)

    if results.detected_objects:
        for obj in results.detected_objects:
            mp_drawing.draw_landmarks(img, obj.landmarks_2d, mp_objectron.BOX_CONNECTIONS)
            mp_drawing.draw_axis(img, obj.rotation, obj.translation)

    frame.image(img, channels="BGR")

cap.release()