# -*- coding: utf-8 -*-
"""3_About.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMUqdBGqXLDdb9IEEdMeiXCmogXbAxXd
"""

import streamlit as st

st.title("ℹ️ About This App")

st.markdown("""
This is a multi-page **Streamlit app** for **real-time AI-based computer vision**.

**Technologies used:**
- [Streamlit](https://streamlit.io) for UI
- [MediaPipe](https://google.github.io/mediapipe/) for ML-powered face and object detection
- [OpenCV](https://opencv.org/) for real-time webcam handling

Created with ❤️ by MennatullahTarek.
""")